name: dev

on: [push]

jobs:

  ubuntu:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display compiler version
        run: g++ --version

      - name: Install MPFR
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmpfr-dev

      - name: Make!
        run: |
          cd hypercomplex
          make help

  conda:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          activate-environment: hypercomplex-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Make!
        run: |
          cd hypercomplex
          make help
