name: docs

on: [push]

jobs:

  gh-pages:
    runs-on: ubuntu-22.04
    env:
      test-directory: .test/docs

    steps:

      - name: Install MPFR
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmpfr-dev

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Files
        working-directory: ${{env.test-directory}}
        run: |
          cp ../../hypercomplex/Hypercomplex.hpp Hypercomplex.hpp
          cp ../../hypercomplex/Polynomial.hpp Polynomial.hpp

      - name: Compile Test Program
        working-directory: ${{env.test-directory}}
        run: g++ --std=c++17 test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        working-directory: ${{env.test-directory}}
        run: ./test

      - name: BuildTheDocs
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: '.'
            doxyfile-path: './Doxyfile'
            enable-latex: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: 'docs'
          destination_dir: 'docs'
          keep_files: true
