name: Include

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set CWD
        run: cd .test/include

      - name: Copy Library Files
        run: |
          cp ../../hypercomplex/hypercomplex.h hypercomplex.h
          cp ../../hypercomplex/hypercomplex.cpp hypercomplex.cpp

      - name: Display compiler version
        run: g++ --version

      - name: Compile Test Program
        run: g++ test.cpp hypercomplex.cpp -o test

      - name: Execute Test Program
        run: ./test
