name: Include

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  Include:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    env:
      working-directory: .test/include

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: g++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: g++ --std=c++17 test.cpp -o test

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test
