name: Install

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  Install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
    env:
      test-directory: .test/install
      lib-directory: "hypercomplex"

    steps:

      - name: Install MPFR
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y libmpfr-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install mpfr
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Make version
        run: make --version

      - name: Display compiler version
        run: g++ --version

      - name: Copy Header-Only Library
        working-directory: ${{env.lib-directory}}
        run: sudo make install

      - name: Compile Test Program
        working-directory: ${{env.test-directory}}
        run: g++ --std=c++17 test.cpp -o test

      - name: Execute Test Program
        working-directory: ${{env.test-directory}}
        run: ./test

      - name: Remove Copied Library
        working-directory: ${{env.lib-directory}}
        run: sudo make uninstall
