name: Install

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    env:
      working-directory: .test/install

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Files
        working-directory: ${{env.working-directory}}
        run: |
          cp ../../hypercomplex/hypercomplex.h hypercomplex.h
          cp ../../hypercomplex/hypercomplex.cpp hypercomplex.cpp

      - name: Display Make version
        run: make --version

      - name: Display compiler version
        run: g++ --version

      - name: Build Static Library
        working-directory: ${{env.working-directory}}
        run: make

      - name: Copy Static Library
        working-directory: ${{env.working-directory}}
        run: make install

      - name: ls
        run: ls ~

      - name: Remove Build Files in CWD
        working-directory: ${{env.working-directory}}
        run: make clean

      - name: Remove Library Files in CWD
        working-directory: ${{env.working-directory}}
        run: |
          rm -f hypercomplex.h
          rm -f hypercomplex.cpp

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: g++ test.cpp -I ~/lib/include/ ~/lib/lib/hypercomplex.a -o test

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test

      - name: Remove Copied Library
        working-directory: ${{env.working-directory}}
        run: make uninstall
