name: cpplint

on: [push]

jobs:
  cpplint:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install cpplint
        run: pip install cpplint

      - name: Static Code Analysis
        run: |
          cd hypercomplex
          /home/runner/.local/bin/cpplint --quiet Hypercomplex.hpp
          /home/runner/.local/bin/cpplint --quiet Polynomial.hpp
