name: cpplint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cpplint:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install cpplint
        run: pip install cpplint

      - name: Static Code Analysis
        run: |
          cd hypercomplex
          /home/runner/.local/bin/cpplint --quiet hypercomplex.h
          /home/runner/.local/bin/cpplint --quiet hypercomplex.cpp
