name: publish

on:
  release:
    types: [published]

jobs:

  gh-pages:
    runs-on: ubuntu-22.04
    env:
      test-directory: .test/docs

    steps:

      - name: Display Compiler Version
        run: g++ --version

      - name: Install MPFR
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmpfr-dev

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Library Files
        working-directory: ${{env.test-directory}}
        run: |
          cp ../../hypercomplex/Hypercomplex.hpp Hypercomplex.hpp
          cp ../../hypercomplex/Polynomial.hpp Polynomial.hpp

      - name: Compile Docs Test Program
        working-directory: ${{env.test-directory}}
        run: g++ --std=c++17 test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        working-directory: ${{env.test-directory}}
        run: ./test

      - name: BuildTheDocs
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: '.'
            doxyfile-path: './Doxyfile'
            enable-latex: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: 'docs'
          destination_dir: 'docs'
          keep_files: true

  Anaconda:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          auto-activate-base: true

      - name: Install conda build suite
        shell: bash -l {0}
        run: conda install anaconda-client conda-build conda-verify numpy

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Render version into the build recipe
        shell: bash -l {0}
        run: |
          VERSION=$(<hypercomplex/VERSION)
          VERSION="${VERSION:1}"
          sed -i "s/{{ version }}/$VERSION/" meta.yaml

      - name: Build Anaconda Package
        shell: bash -l {0}
        run: conda build . -c conda-forge

      - name: Upload to Anaconda.org
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda config --set anaconda_upload yes
          anaconda upload --user AngryMaciek hypercomplex

  DockerHub:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build & Publish image to DockerHub
        env:
          docker_username: angrymaciek
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          repo_name="hypercomplex"
          tag=${GITHUB_REF##*/}
          tag="${tag:1}"
          docker build -t angrymaciek/${repo_name}:latest .
          docker tag angrymaciek/${repo_name} angrymaciek/${repo_name}:${tag}
          echo $docker_password | docker login -u $docker_username --password-stdin
          docker push angrymaciek/${repo_name}:${tag}

  CHANGELOG:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}

      - name: Update CHANGELOG
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          excludeTypes: docs,other
          includeRefIssues: false
          reverseOrder: true

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_user_name: AngryMaciek
          commit_user_email: wsciekly.maciek@gmail.com
          commit_message: 'docs: CHANGELOG.md auto update'
          push_options: --force
