name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  gh-pages:

    runs-on: ubuntu-22.04
    env:
      test-directory: .test/docs

    steps:

      - name: Install MPFR
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmpfr-dev

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Files
        working-directory: ${{env.test-directory}}
        run: |
          cp ../../hypercomplex/Hypercomplex.hpp Hypercomplex.hpp
          cp ../../hypercomplex/Polynomial.hpp Polynomial.hpp

      - name: Compile Test Program
        working-directory: ${{env.test-directory}}
        run: g++ --std=c++17 test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        working-directory: ${{env.test-directory}}
        run: ./test

      - name: BuildTheDocs
        uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: '.'
            doxyfile-path: './Doxyfile'
            enable-latex: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: 'docs'
          destination_dir: 'docs'
          keep_files: true

  conda:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          auto-activate-base: true

      - name: Install conda build suite
        shell: bash -l {0}
        run: conda install conda-build conda-verify numpy

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Render version into the build recipe
        shell: bash -l {0}
        run: |
          VERSION=$(<VERSION)
          echo $VERSION
          sed -i "s/{{ version }}/$VERSION/" meta.yaml
          cat meta.yaml

      - name: Build Anaconda Package
        shell: bash -l {0}
        run: conda build . -c conda-forge

      # push to cloud
