name: Shared Library

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: macos-10.15
    env:
      working-directory: ./hypercomplex

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display compiler version
        run: g++ --version

      - name: Create MD5 Checksum
        working-directory: ${{env.working-directory}}
        run: md5sum Hypercomplex.so > Hypercomplex.so.txt

      - name: Rebuild Library
        working-directory: ${{env.working-directory}}
        run: g++ -Wall -shared -o Hypercomplex.so -fPIC Hypercomplex.cpp -std=c++11

      - name: Compare MD5 Checksum
        working-directory: ${{env.working-directory}}
        run: md5sum --check Hypercomplex.so.txt
