name: Catch2

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:

  platform-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
      fail-fast: false
    env:
      working-directory: .test/unit

    steps:

      - name: Install Clang & MPFR
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y libmpfr-dev clang
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install mpfr
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: clang++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: clang++ -O0 -Wall --std=c++17 -o test test.cpp -lmpfr -lgmp -fconstexpr-steps=4294967295

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test -d yes -w NoAssertions --use-colour yes --benchmark-samples 100 --benchmark-resamples 100000

  code-coverage:
    runs-on: ubuntu-22.04
    env:
      working-directory: .test/unit

    steps:

      - name: Install lcov
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lcov

      - name: Install Clang & MPFR
        run: sudo apt-get install -y libmpfr-dev clang

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: clang++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: clang++ -O0 -fprofile-arcs -ftest-coverage -Wall --std=c++17 --coverage -o test test.cpp -lmpfr -lgmp -fconstexpr-steps=4294967295

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test

      - name: Generate Coverage Report
        working-directory: ${{env.working-directory}}
        run: |
          gcov test.cpp
          lcov --capture --directory . --output-file coverage.info
          rm -rf *.gcov test.gc*

      - name: Submit Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .test/unit/coverage.info
          fail_ci_if_error: true
          verbose: true

  memcheck:
    runs-on: ubuntu-22.04
    env:
      working-directory: .test/unit

    steps:

      - name: Install Clang & MPFR
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libmpfr-dev clang

      - name: Install Valgrind
        run: sudo apt install -y valgrind

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: clang++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: clang++ -O0 -Wall --std=c++17 -o test test.cpp -lmpfr -lgmp -fconstexpr-steps=4294967295

      - name: Analyze Test Program Execution
        working-directory: ${{env.working-directory}}
        run: |
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind.txt ./test
          cat valgrind.txt
          grep -q -w "All heap blocks were freed -- no leaks are possible" "valgrind.txt"
