name: unit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  platform-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    env:
      working-directory: .test/unit

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -S. -DBUILD_TESTING=OFF
          cmake --build build/ --target install
          cd ..
          rm -rf Catch2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: g++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: g++ test.cpp hypercomplex/hypercomplex.cpp -o test

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test

  code-coverage:
    runs-on: ubuntu-20.04
    env:
      working-directory: .test/unit

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Display compiler version
        run: g++ --version

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: g++ test.cpp hypercomplex/hypercomplex.cpp --coverage -o test

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test

      - name: Generate Coverage Report
        run: gcov -o . test.cpp

      - name: Submit Report to Codecov
        working-directory: ${{env.working-directory}}
        run: |
          CODECOV_TOKEN="b4d8e754-58fe-4412-ab69-d8b7d368d8f4"
          bash <(curl -s https://codecov.io/bash)
