name: Install&Include

on: [push]

jobs:

  include:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04]
      fail-fast: false
    env:
      working-directory: .test/include

    steps:

      - name: Display Compiler Version
        run: g++ --version

      - name: Install MPFR
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y libmpfr-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install mpfr
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Library Directory
        working-directory: ${{env.working-directory}}
        run: cp -r ../../hypercomplex hypercomplex

      - name: Compile Test Program
        working-directory: ${{env.working-directory}}
        run: g++ --std=c++17 test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        working-directory: ${{env.working-directory}}
        run: ./test

  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04]
      fail-fast: false
    env:
      test-directory: .test/install

    steps:

      - name: Display Compiler Version
        run: g++ --version

      - name: Install MPFR
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y libmpfr-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install mpfr
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Library
        run: sudo make install

      - name: Compile Test Program
        working-directory: ${{env.test-directory}}
        run: g++ --std=c++17 test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        working-directory: ${{env.test-directory}}
        run: ./test

      - name: Uninstall Library
        run: sudo make uninstall

  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04]
      fail-fast: false

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          auto-activate-base: true

      - name: Install Conda Build Suite
        shell: bash -l {0}
        run: conda install conda-build conda-verify numpy

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Build Conda Package
        shell: bash -l {0}
        run: conda build . -c conda-forge

      - name: Install Package
        shell: bash -l {0}
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ -c conda-forge hypercomplex --yes

      - name: Compile Test Program
        shell: bash -l {0}
        run: g++ --std=c++17 -I$CONDA_PREFIX/include -L$CONDA_PREFIX/lib .test/install/test.cpp -o test -lmpfr -lgmp

      - name: Execute Test Program
        shell: bash -l {0}
        run: ./test
